version: '3'

volumes:
  image-data:

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network

  sorter:
    build: sorter
    environment:
      RABBITMQ_HOSTNAME: 'rabbitmq'
    networks:
      - network
    depends_on:
      - rabbitmq
    volumes:
    - "./images:/usr/src/app/images"

  dumper:
    build: dumper
    environment:
      RABBITMQ_HOSTNAME: 'rabbitmq'
    networks:
      - network
    depends_on:
      - rabbitmq
      - sorter
    volumes:
    - "./images:/usr/src/app/images"

networks:
  network: {}