version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network

  sorter:
    build: sorter
    environment:
      RABBITMQ_HOSTNAME: 'rabbitmq'
    networks:
      - network
    depends_on:
      - rabbitmq

  dumper:
    build: dumper
    environment:
      RABBITMQ_HOSTNAME: 'rabbitmq'
    networks:
      - network
    depends_on:
      - rabbitmq

networks:
  network: {}